"""Provider control center: fleet telemetry, routing, and safe configuration."""

from __future__ import annotations


def content() -> str:
    """Return the provider control-center body."""
    return """
    <section class="page-head provider-hero">
      <div>
        <p class="eyebrow">PRV&middot;CONTROL</p>
        <h2>Provider control center</h2>
        <p class="muted">One operational view for model traffic, provider health, rate capacity, account balancing, failover policy, and agent orchestration.</p>
      </div>
      <div class="page-head-actions provider-refresh-controls">
        <label class="auto-refresh"><input id="providers-auto-refresh" type="checkbox" checked> Auto-refresh</label>
        <button id="providers-refresh" type="button" class="secondary">Refresh now</button>
        <span id="provider-health" class="pill">Loading</span>
      </div>
    </section>
    <section class="provider-kpis" id="provider-kpis" aria-label="Provider fleet summary">
      <div class="provider-kpi"><span class="kpi-label">Fleet online</span><strong id="kpi-online">&mdash;</strong><span id="kpi-online-note" class="kpi-note">loading</span></div>
      <div class="provider-kpi"><span class="kpi-label">Total calls</span><strong id="kpi-calls">&mdash;</strong><span class="kpi-note">lifetime</span></div>
      <div class="provider-kpi"><span class="kpi-label">Tokens</span><strong id="kpi-tokens">&mdash;</strong><span class="kpi-note">prompt + completion</span></div>
      <div class="provider-kpi"><span class="kpi-label">Spend</span><strong id="kpi-spend">&mdash;</strong><span class="kpi-note">recorded lifetime</span></div>
      <div class="provider-kpi"><span class="kpi-label">Accounts healthy</span><strong id="kpi-accounts">&mdash;</strong><span class="kpi-note">balanced credentials</span></div>
      <div class="provider-kpi"><span class="kpi-label">Last sync</span><strong id="kpi-sync">&mdash;</strong><span class="kpi-note">30 second cadence</span></div>
    </section>
    <div class="provider-dashboard-grid">
      <section class="panel provider-traffic-panel" aria-labelledby="usage-heading">
        <div class="panel-head">
          <div class="panel-id"><span class="mod-code">PRV&middot;01</span><h3 id="usage-heading">Traffic &amp; spend</h3></div>
          <div class="usage-metric-toggle" id="usage-metric-toggle">
            <button type="button" class="secondary small active" data-metric="call_count">Calls</button>
            <button type="button" class="secondary small" data-metric="total_tokens">Tokens</button>
            <button type="button" class="secondary small" data-metric="total_cost_usd">Cost</button>
          </div>
          <select id="usage-days" aria-label="Usage time range"><option value="7">7 days</option><option value="14" selected>14 days</option><option value="30">30 days</option><option value="90">90 days</option></select>
        </div>
        <p class="muted">Daily provider contribution. Toggle a legend item to focus the graph.</p>
        <div class="usage-chart-wrap"><div id="usage-chart"><div class="empty">Loading usage&hellip;</div></div></div>
        <div class="usage-legend" id="usage-legend"></div>
      </section>
      <section class="panel provider-policy-panel" aria-labelledby="policy-heading">
        <div class="panel-head"><div class="panel-id"><span class="mod-code">PRV&middot;02</span><h3 id="policy-heading">Agent orchestration</h3></div><span class="pill ok">hot reload</span></div>
        <p class="muted">Limits apply across the running agent and delegated work. Zero-dollar budgets mean unlimited.</p>
        <div id="agent-settings"><div class="empty">Loading agent settings&hellip;</div></div>
      </section>
    </div>
    <section class="panel" aria-labelledby="fleet-heading">
      <div class="panel-head"><div class="panel-id"><span class="mod-code">PRV&middot;03</span><h3 id="fleet-heading">Provider fleet</h3></div><span id="provider-default" class="pill">&mdash;</span></div>
      <p class="muted">The default is sticky. Weight controls proportional selection only when fallback/balancing chooses among eligible providers.</p>
      <div id="providers" class="provider-fleet"><div class="empty">Loading providers&hellip;</div></div>
    </section>
    <section class="panel" aria-labelledby="balancing-heading">
      <div class="panel-head"><div class="panel-id"><span class="mod-code">PRV&middot;04</span><h3 id="balancing-heading">Routing &amp; account balancing</h3></div><span class="pill">live capacity</span></div>
      <p class="muted">Cross-provider share is based on enabled weights. Account lanes show credential health, configured share, remaining capacity, usage, and last activity without exposing secrets.</p>
      <div id="balancing-board"><div class="empty">Loading routing state&hellip;</div></div>
    </section>
    """


def script() -> str:
    """Return the provider control-center browser logic."""
    return r"""
let latestUsage = null;
let chartMetric = 'call_count';
let chartDays = 14;
let autoRefreshTimer = null;
const hiddenProviders = new Set();
const PALETTE = ['#4fb3ff', '#3ddc84', '#f5b942', '#ef5350', '#a78bfa', '#f472b6', '#22d3ee', '#fb923c'];
function colorForProvider(name) { let hash=0; for(let i=0;i<name.length;i++) hash=(hash*31+name.charCodeAt(i))>>>0; return PALETTE[hash%PALETTE.length]; }
function fmtNum(value) { return Number(value||0).toLocaleString(); }
function fmtUsd(value) { const number=Number(value||0); return '$'+number.toFixed(number<1?4:2); }
function fmtPct(value) { return Number(value||0).toFixed(1)+'%'; }
function fmtTime(value) { if(!value) return 'never'; const date=new Date(value); return Number.isNaN(date.getTime())?String(value):date.toLocaleString(); }
function usageStat(label,value,detail='') { return `<div class="usage-stat"><span class="value">${esc(value)}</span><span class="label">${esc(label)}</span>${detail?`<span class="detail">${esc(detail)}</span>`:''}</div>`; }
function capacityBar(label,capacity,limit,unlimited) {
  if(unlimited) return `<div class="usage-bar-row"><div class="usage-bar-label"><span>${esc(label)}</span><span>unlimited</span></div><div class="usage-bar unlimited"><div class="usage-bar-fill"></div></div></div>`;
  if(!limit) return `<div class="usage-bar-row"><div class="usage-bar-label"><span>${esc(label)}</span><span>not configured</span></div></div>`;
  const pct=Math.max(0,Math.min(100,(Number(capacity||0)/Number(limit))*100)); const cls=pct<15?'crit':(pct<40?'warn':'');
  return `<div class="usage-bar-row"><div class="usage-bar-label"><span>${esc(label)}</span><span>${fmtNum(Math.round(capacity||0))} / ${fmtNum(limit)} · ${fmtPct(pct)}</span></div><div class="usage-bar"><div class="usage-bar-fill ${cls}" style="width:${pct.toFixed(1)}%"></div></div></div>`;
}
function rateLimitBars(rate) { if(!rate) return '<p class="muted compact">Runtime capacity is not reported.</p>'; return capacityBar('Requests/min',rate.request_capacity,rate.requests_per_minute,rate.request_unlimited)+capacityBar('Tokens/min',rate.token_capacity,rate.tokens_per_minute,rate.token_unlimited); }
function renderKpis() {
  const summary=latestUsage.summary||{}, totals=latestUsage.totals||{};
  setText('kpi-online',`${summary.available_count||0}/${summary.provider_count||0}`); setText('kpi-online-note',summary.degraded_count?`${summary.degraded_count} degraded`:'all enabled providers ready');
  setText('kpi-calls',fmtNum(totals.call_count)); setText('kpi-tokens',fmtNum((totals.total_prompt_tokens||0)+(totals.total_completion_tokens||0))); setText('kpi-spend',fmtUsd(totals.total_cost_usd));
  setText('kpi-accounts',summary.account_count?`${summary.healthy_account_count||0}/${summary.account_count}`:'n/a'); setText('kpi-sync',new Date(latestUsage.generated_at||Date.now()).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}));
}
function renderChartLegend() { const providers=latestUsage.providers||[]; document.getElementById('usage-legend').innerHTML=providers.map(provider=>`<button type="button" class="usage-legend-item${hiddenProviders.has(provider.name)?' off':''}" data-legend="${esc(provider.name)}"><span class="usage-legend-swatch" style="background:${colorForProvider(provider.name)}"></span>${esc(provider.name)}</button>`).join(''); }
function renderChart() {
  const container=document.getElementById('usage-chart'),series=latestUsage.series||[],names=(latestUsage.providers||[]).map(p=>p.name).filter(name=>!hiddenProviders.has(name));
  if(!series.length||!names.length){container.innerHTML='<div class="usage-chart-empty muted">No attributed usage in this window.</div>';return;}
  const dates=[...new Set(series.map(row=>row.date))].sort(),index={}; for(const row of series){index[row.date]=index[row.date]||{};index[row.date][row.provider]=row;}
  const totals=dates.map(date=>names.reduce((sum,name)=>sum+Number((index[date]?.[name]||{})[chartMetric]||0),0)),maxTotal=Math.max(1,...totals),barWidth=26,gap=10,left=50,bottom=25,top=12,height=215,width=left+dates.length*(barWidth+gap),every=Math.max(1,Math.ceil(dates.length/14)); let marks='';
  dates.forEach((date,position)=>{const x=left+position*(barWidth+gap);let y=height-bottom;names.forEach(name=>{const value=Number((index[date]?.[name]||{})[chartMetric]||0);if(value<=0)return;const segment=value/maxTotal*(height-top-bottom);y-=segment;const formatted=chartMetric==='total_cost_usd'?fmtUsd(value):fmtNum(value);marks+=`<rect x="${x}" y="${y.toFixed(1)}" width="${barWidth}" height="${segment.toFixed(1)}" fill="${colorForProvider(name)}" rx="2"><title>${esc(name)} · ${esc(date)} · ${esc(formatted)}</title></rect>`;});if(position%every===0)marks+=`<text x="${x+barWidth/2}" y="${height-6}" text-anchor="middle" font-size="10" fill="var(--muted)" font-family="var(--mono)">${esc(date.slice(5))}</text>`;});
  const peak=chartMetric==='total_cost_usd'?fmtUsd(maxTotal):fmtNum(maxTotal); container.innerHTML=`<svg viewBox="0 0 ${width} ${height}" width="${width}" height="${height}" role="img" aria-label="Provider usage"><line x1="${left-6}" y1="${height-bottom}" x2="${width}" y2="${height-bottom}" stroke="var(--line)"/><text x="4" y="${top+8}" font-size="10" fill="var(--muted)" font-family="var(--mono)">${esc(peak)}</text>${marks}</svg>`;
}
function providerCard(provider) {
  const usage=provider.usage||{},config=provider.config||{},status=!provider.enabled?['crit','disabled']:provider.available?['ok','online']:['warn','degraded'],breaker=provider.circuit_breaker||{state:'not_observed',failure_count:0};
  const calls=Number(usage.call_count||0),callShare=Number(latestUsage.totals?.call_count||0)?calls/Number(latestUsage.totals.call_count)*100:0,avgTokens=calls?Number(usage.total_tokens||0)/calls:0,avgCost=calls?Number(usage.total_cost_usd||0)/calls:0,authCount=Number(config.oauth_accounts_count||config.api_keys_count||(config.api_key_configured?1:0)),toggleDisabled=provider.enabled&&provider.is_default?'disabled title="Switch the default before disabling"':'';
  return `<article class="provider-control-card" style="--provider-color:${colorForProvider(provider.name)}"><div class="provider-control-head"><button class="provider-name" type="button" data-provider-detail="${esc(provider.name)}"><span class="led ${status[0]}"></span><span>${esc(provider.name)}</span></button>${provider.is_default?'<span class="pill ok">default</span>':''}<span class="pill ${breaker.state==='open'?'crit':''}">circuit ${esc(breaker.state)}</span><span class="provider-state">${esc(status[1])}</span></div><div class="provider-model-stack"><strong>${esc(provider.model||'model unset')}</strong><span>fast: ${esc(config.fast_model||'inherit')}</span><span>premium: ${esc(config.premium_model||'inherit')}</span></div><div class="provider-stat-row">${usageStat('calls',fmtNum(usage.call_count),`${fmtPct(callShare)} share`)}${usageStat('tokens',fmtNum(usage.total_tokens),`${fmtNum(Math.round(avgTokens))} avg/call`)}${usageStat('cost',fmtUsd(usage.total_cost_usd),`${fmtUsd(avgCost)} avg/call`)}${usageStat('accounts',authCount||'env/default',config.key_rotation_strategy||'failover')}</div><div class="provider-capacity">${rateLimitBars(provider.rate_limit)}</div><div class="provider-config-strip"><span>timeout <b>${esc(config.timeout??'—')}s</b></span><span>max wait <b>${esc(config.max_wait_seconds??'—')}s</b></span><span>breaker <b>${esc(config.circuit_breaker_threshold??'—')} / ${esc(config.circuit_breaker_cooldown_seconds??'—')}s</b></span><span>last call <b>${esc(fmtTime(usage.last_call))}</b></span></div><div class="provider-card-actions"><button class="secondary small provider-default" type="button" data-provider="${esc(provider.name)}" ${provider.is_default||!provider.enabled||!provider.available?'disabled':''}>Make default</button><button class="secondary small ${provider.enabled?'danger':''} provider-toggle" type="button" data-provider="${esc(provider.name)}" data-enable="${provider.enabled?'0':'1'}" ${toggleDisabled}>${provider.enabled?'Disable':'Enable'}</button><label class="provider-weight-label">Routing weight<input class="provider-weight-input" type="number" min="0" step="0.1" value="${esc(provider.weight??1)}" aria-label="Routing weight for ${esc(provider.name)}"></label><button class="secondary small provider-weight-set" type="button" data-provider="${esc(provider.name)}">Apply weight</button><button class="secondary small" type="button" data-provider-detail="${esc(provider.name)}">Configure</button></div></article>`;
}
function accountLane(provider,account) { const usage=account.usage||{},state=account.healthy?(account.client_ready?['ok','healthy']:['warn','idle']):['crit','backing off']; return `<div class="account-lane"><div class="account-lane-head"><span class="led ${state[0]}"></span><strong>${esc(account.name)}</strong><span class="pill">${esc(state[1])}</span><span class="account-weight">weight ${esc(account.weight??1)}</span></div><div class="account-lane-meta"><span>${fmtNum(usage.call_count)} calls</span><span>${fmtNum(usage.total_tokens)} tokens</span><span>${fmtUsd(usage.total_cost_usd)}</span><span>${esc(fmtTime(usage.last_call))}</span></div>${rateLimitBars(account.rate_limit)}</div>`; }
function renderBalancing() {
  const providers=latestUsage.providers||[],eligible=providers.filter(provider=>provider.enabled&&provider.available&&Number(provider.weight||0)>0),totalWeight=eligible.reduce((sum,provider)=>sum+Number(provider.weight||0),0);
  const routes=providers.map(provider=>{const share=totalWeight&&eligible.includes(provider)?Number(provider.weight||0)/totalWeight*100:0;return `<div class="route-row"><span class="route-provider"><span class="usage-legend-swatch" style="background:${colorForProvider(provider.name)}"></span><strong>${esc(provider.name)}</strong>${provider.is_default?'<span class="pill ok">default</span>':''}</span><div class="route-track"><span style="width:${share}%"></span></div><span class="route-share">${fmtPct(share)} · w ${esc(provider.weight??1)}</span></div>`;}).join('');
  const groups=providers.filter(provider=>provider.accounts?.length).map(provider=>`<div class="account-group"><div class="account-group-head"><strong>${esc(provider.name)}</strong><span>${esc(provider.config?.key_rotation_strategy||'failover')} · ${provider.accounts.length} accounts</span></div>${provider.accounts.map(account=>accountLane(provider,account)).join('')}<button class="secondary small account-weights-open" type="button" data-provider-detail="${esc(provider.name)}">Edit account weights</button></div>`).join('');
  document.getElementById('balancing-board').innerHTML=`<div class="balancing-columns"><div><h4>Eligible provider share</h4><p class="muted compact">Projected weighted share after the sticky default cannot serve a request.</p><div class="route-list">${routes||empty('No providers registered.')}</div></div><div><h4>Account lanes</h4><p class="muted compact">Health and quotas are independent per account.</p><div class="account-groups">${groups||empty('No multi-account round-robin providers are active.')}</div></div></div>`;
}
const AGENT_FIELDS=[['max_iterations','Max tool-loop iterations','number',1,1],['temperature','Sampling temperature','number',0,0.1],['max_sub_agents','Max agents per delegation','number',1,1],['max_concurrent_agents','Max concurrent agents','number',1,1],['max_sub_agent_depth','Delegation depth','number',0,1],['max_spend_usd','Per-session budget (USD)','number',0,0.01],['global_max_spend_usd','Global budget (USD)','number',0,0.01]];
function renderAgentSettings() { const settings=latestUsage.agent_settings||{},fields=AGENT_FIELDS.map(([key,label,type,min,step])=>`<label class="agent-setting"><span>${esc(label)}</span><input type="${type}" min="${min}" step="${step}" value="${esc(settings[key]??'')}" data-agent-field="${key}" data-original="${esc(settings[key]??'')}"></label>`).join(''); document.getElementById('agent-settings').innerHTML=`<form id="agent-settings-form" class="agent-settings-form">${fields}<label class="agent-setting"><span>Global budget period</span><select data-agent-field="global_budget_period" data-original="${esc(settings.global_budget_period||'total')}">${['total','daily','monthly'].map(value=>`<option value="${value}" ${settings.global_budget_period===value?'selected':''}>${value}</option>`).join('')}</select></label><div class="agent-setting-readonly"><span>Complexity model routing</span><strong>${settings.model_routing_enabled?'enabled':'disabled'}</strong></div><div class="agent-settings-actions"><span class="muted compact">Changes are backed up and hot-reloaded.</span><button type="submit" class="secondary small">Save agent settings</button></div></form>`; }
const EDITABLE_FIELDS=[['model','Primary model','text'],['fast_model','Fast model','text'],['premium_model','Premium model','text'],['context_worker_provider','Context worker provider','text'],['context_worker_model','Context worker model','text'],['base_url','Base URL override','text'],['timeout','Request timeout (s)','number'],['requests_per_minute','Requests/min (0 unlimited)','number'],['tokens_per_minute','Tokens/min (0 unlimited)','number'],['max_wait_seconds','Capacity wait ceiling (s)','number'],['circuit_breaker_threshold','Breaker failure threshold','number'],['circuit_breaker_cooldown_seconds','Breaker cooldown (s)','number']];
function providerEditForm(name,config,accounts) { const rows=EDITABLE_FIELDS.map(([key,label,type])=>`<label><span class="field-label">${esc(label)}</span><input type="${type}" ${type==='number'?'min="0" step="any"':''} value="${esc(config[key]??'')}" data-field="${key}" data-original="${esc(config[key]??'')}"></label>`).join(''),rotation=`<label><span class="field-label">Account strategy</span><select data-field="key_rotation_strategy" data-original="${esc(config.key_rotation_strategy||'failover')}"><option value="failover" ${config.key_rotation_strategy!=='round_robin'?'selected':''}>failover</option><option value="round_robin" ${config.key_rotation_strategy==='round_robin'?'selected':''}>round robin</option></select></label>`,weights=accounts?.length?`<label class="provider-account-weights"><span class="field-label">Account weights (${accounts.map(a=>a.name).join(', ')})</span><input type="text" value="${esc(accounts.map(a=>a.weight??1).join(', '))}" data-account-weights data-original="${esc(accounts.map(a=>a.weight??1).join(', '))}"><span class="muted compact">Comma-separated positive values, in account order.</span></label>`:''; return `<form class="provider-edit-form" data-provider="${esc(name)}"><div class="provider-edit-grid">${rows}${rotation}${weights}</div><div class="op-form-actions"><button type="submit" class="secondary small">Save provider configuration</button></div></form>`; }
function accountDetail(account) { const usage=account.usage||{}; return `<div class="account-card"><div class="account-card-head"><span class="led ${account.healthy?'ok':'crit'}"></span><strong>${esc(account.name)}</strong><span class="pill">weight ${esc(account.weight??1)}</span></div><div class="provider-stat-row">${usageStat('calls',fmtNum(usage.call_count))}${usageStat('prompt',fmtNum(usage.total_prompt_tokens))}${usageStat('completion',fmtNum(usage.total_completion_tokens))}${usageStat('cost',fmtUsd(usage.total_cost_usd))}</div>${rateLimitBars(account.rate_limit)}<p class="muted compact">Last call: ${esc(fmtTime(usage.last_call))} · failures: ${esc(account.consecutive_failures||0)}</p></div>`; }
async function openProviderInspector(name) {
  openInspector('PRV',name,'Loading provider control plane…',empty('Loading provider detail…'));
  try { const response=await api('/providers/' + encodeURIComponent(name)),provider=response.data,config=provider.config||{},usage=provider.usage||{},credentials=config.oauth_accounts_count?`${config.oauth_accounts_count} OAuth accounts`:config.api_keys_count?`${config.api_keys_count} configured keys`:config.api_key_configured?'configured':'environment/default',accounts=provider.accounts||[];
    const body=`<div class="inspector-summary-grid">${inspectorField('Runtime status',provider.enabled?(provider.available?'Online':'Degraded'):'Disabled')}${inspectorField('Default',provider.is_default?'Yes':'No')}${inspectorField('Credentials',credentials)}${inspectorField('Circuit',`${provider.circuit_breaker?.state||'unknown'} · ${provider.circuit_breaker?.failure_count||0} failures`)}</div>`+`<div class="field-block"><span class="field-label">Lifetime usage</span><div class="provider-stat-row">${usageStat('calls',fmtNum(usage.call_count))}${usageStat('prompt tokens',fmtNum(usage.total_prompt_tokens))}${usageStat('completion tokens',fmtNum(usage.total_completion_tokens))}${usageStat('cost',fmtUsd(usage.total_cost_usd))}</div></div>`+`<div class="field-block"><span class="field-label">Live capacity</span>${rateLimitBars(provider.rate_limit)}</div>`+(accounts.length?`<div class="field-block"><span class="field-label">Account telemetry</span><div class="account-list">${accounts.map(accountDetail).join('')}</div></div>`:'')+`<div class="field-block"><span class="field-label">Safe configuration</span><p class="muted compact">Credential material is never returned to this page. Use the provider auth CLI to change secrets.</p>${providerEditForm(provider.name,config,accounts)}</div>`+(provider.diagnostics?inspectorJson('Redacted diagnostics',provider.diagnostics):'');
    openInspector('PRV',provider.name,`${provider.model||config.model||'model unset'} · ${provider.available?'online':'offline'}`,body);
  } catch(error){openInspector('PRV',name,'Error',empty('Could not load provider: '+error.message));}
}
async function loadProviders() {
  const refresh=document.getElementById('providers-refresh');refresh.disabled=true;
  try { const response=await api(`/providers/usage?days=${chartDays}`);latestUsage=response.data;const providers=latestUsage.providers||[];renderKpis();renderChartLegend();renderChart();renderAgentSettings();renderBalancing();document.getElementById('providers').innerHTML=providers.length?providers.map(providerCard).join(''):empty('No providers registered.');const summary=latestUsage.summary||{};setText('provider-health',summary.degraded_count?`${summary.degraded_count} degraded`:`${summary.available_count||0}/${summary.provider_count||0} online`);document.getElementById('provider-health').className=`pill ${summary.degraded_count?'warn':'ok'}`;const current=providers.find(provider=>provider.is_default);setText('provider-default',current?`default · ${current.name}`:'no default'); }
  catch(error){setText('provider-health','Unavailable');document.getElementById('providers').innerHTML=empty('Provider control plane unavailable: '+error.message);document.getElementById('balancing-board').innerHTML=empty('Routing state unavailable.');}
  finally{refresh.disabled=false;}
}
document.getElementById('providers').addEventListener('click',async event=>{
  const detail=event.target.closest('[data-provider-detail]');if(detail){openProviderInspector(detail.dataset.providerDetail);return;}
  const defaultButton=event.target.closest('.provider-default');if(defaultButton&&!defaultButton.disabled){const name=defaultButton.dataset.provider;if(!window.confirm(`Make ${name} the sticky default provider?`))return;try{await api('/controls/provider.set_default',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target:name,confirm:'set-default:' + name})});await loadProviders();}catch(error){window.alert('Could not set default: '+error.message);}return;}
  const toggle=event.target.closest('.provider-toggle');if(toggle&&!toggle.disabled){const name=toggle.dataset.provider,action=toggle.dataset.enable==='1'?'enable':'disable';if(!window.confirm(`${action==='enable'?'Enable':'Disable'} ${name}?`))return;try{await api('/controls/provider.'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target:name,confirm:action + '-provider:' + name})});await loadProviders();}catch(error){window.alert(`Could not ${action} provider: `+error.message);}return;}
  const weightButton=event.target.closest('.provider-weight-set');if(weightButton){const name=weightButton.dataset.provider,input=weightButton.closest('.provider-control-card').querySelector('.provider-weight-input'),value=Number(input.value);if(!Number.isFinite(value)||value<0){window.alert('Weight must be a number >= 0.');return;}if(!window.confirm(`Set ${name} routing weight to ${value}?`))return;try{await api('/controls/provider.set_weight',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target:name,value,confirm:`set-weight:${name}:${value}`})});await loadProviders();}catch(error){window.alert('Could not set weight: '+error.message);}}
});
document.getElementById('balancing-board').addEventListener('click',event=>{const button=event.target.closest('[data-provider-detail]');if(button)openProviderInspector(button.dataset.providerDetail);});
document.getElementById('agent-settings').addEventListener('submit',async event=>{const form=event.target.closest('#agent-settings-form');if(!form)return;event.preventDefault();const changes=[...form.querySelectorAll('[data-agent-field]')].map(input=>({field:input.dataset.agentField,value:input.value,original:input.dataset.original})).filter(change=>change.value!==change.original);if(!changes.length){window.alert('No agent settings changed.');return;}if(!window.confirm('Save these agent orchestration changes?\n\n'+changes.map(c=>`${c.field}: ${c.original} → ${c.value}`).join('\n')))return;const maxAgents=changes.find(change=>change.field==='max_sub_agents'),concurrency=changes.find(change=>change.field==='max_concurrent_agents');if(maxAgents&&concurrency){const first=Number(maxAgents.value)<Number(maxAgents.original)?concurrency:maxAgents,second=first===maxAgents?concurrency:maxAgents;changes.splice(changes.indexOf(first),1);changes.splice(changes.indexOf(second),1);changes.unshift(first,second);}try{for(const change of changes)await api('/controls/agent.set_field',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({field:change.field,value:change.value,confirm:`set-agent-field:${change.field}:${change.value}`})});await loadProviders();}catch(error){window.alert('Could not save agent settings: '+error.message);}});
document.getElementById('inspector-body').addEventListener('submit',async event=>{const form=event.target.closest('.provider-edit-form');if(!form)return;event.preventDefault();const name=form.dataset.provider,changes=[...form.querySelectorAll('[data-field]')].map(input=>({field:input.dataset.field,value:input.value,original:input.dataset.original})).filter(change=>change.value!==change.original),weightInput=form.querySelector('[data-account-weights]'),weightsChanged=weightInput&&weightInput.value!==weightInput.dataset.original;if(!changes.length&&!weightsChanged){window.alert('No provider settings changed.');return;}if(!window.confirm(`Save configuration changes for ${name}?`))return;try{for(const change of changes)await api('/controls/provider.set_field',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target:name,field:change.field,value:change.value,confirm:`set-field:${name}:${change.field}:${change.value}`})});if(weightsChanged){const weights=weightInput.value.trim()?weightInput.value.split(',').map(value=>Number(value.trim())):[];if(weights.some(value=>!Number.isFinite(value)||value<=0))throw new Error('Account weights must be positive numbers.');const normalized=weights.map(value=>Number(value).toString()).join(',');await api('/controls/provider.set_account_weights',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target:name,value:weights,confirm:`set-account-weights:${name}:${normalized}`})});}await loadProviders();await openProviderInspector(name);}catch(error){window.alert('Could not save provider configuration: '+error.message);}});
document.getElementById('usage-legend').addEventListener('click',event=>{const item=event.target.closest('[data-legend]');if(!item)return;hiddenProviders.has(item.dataset.legend)?hiddenProviders.delete(item.dataset.legend):hiddenProviders.add(item.dataset.legend);renderChartLegend();renderChart();});
document.getElementById('usage-metric-toggle').addEventListener('click',event=>{const button=event.target.closest('[data-metric]');if(!button)return;chartMetric=button.dataset.metric;document.querySelectorAll('#usage-metric-toggle button').forEach(item=>item.classList.toggle('active',item===button));renderChart();});
document.getElementById('usage-days').addEventListener('change',event=>{chartDays=parseInt(event.target.value,10)||14;loadProviders();});document.getElementById('providers-refresh').addEventListener('click',loadProviders);
document.getElementById('providers-auto-refresh').addEventListener('change',event=>{if(autoRefreshTimer)clearInterval(autoRefreshTimer);autoRefreshTimer=event.target.checked?setInterval(loadProviders,30000):null;});autoRefreshTimer=setInterval(loadProviders,30000);loadProviders();
"""
