"""Anthropic / Claude authentication helpers for the Missy wizard.

Anthropic supports two credential types:

1. **API key** (``sk-ant-api03-...``) — standard, always valid, no ToS concerns.
   Loaded from config, ``ANTHROPIC_API_KEY`` env var, or the encrypted vault.

2. **OAuth setup-token** (``sk-ant-oat01-...``) — generated by the official
   Claude Code CLI via ``claude setup-token``.  This token is a short-lived
   opaque bearer token (≈3-hour lifetime).

   Unlike OpenAI's OAuth flow, Anthropic's authorization redirect goes to
   ``https://platform.claude.com/oauth/code/callback`` — **not** a localhost
   URI — so there is no local callback server.  The user must generate the
   token themselves using the Claude Code CLI and paste it here.

   .. warning::

       Anthropic updated their Terms of Service on **February 19, 2026** to
       prohibit the use of OAuth setup-tokens in third-party tools.  Using
       a setup-token in Missy may violate the Anthropic ToS.  The **API key**
       path is the fully compliant option.  This module implements the
       setup-token paste flow for users who accept that risk, with a
       mandatory acknowledgement prompt.

Token storage
-------------
Tokens are persisted at ``~/.missy/secrets/anthropic-token.json`` with mode
0o600.  The ``vault://`` reference scheme is supported — if the user opts in,
the token/key is stored in the Missy encrypted vault and only a
``vault://anthropic_api_key`` reference is written to ``config.yaml``.

Refresh
-------
Setup-tokens expire after ≈3 hours.  :func:`is_token_expiring` checks the
stored timestamp; :func:`remind_refresh` prints a renewal reminder.
There is no automatic refresh — the user must re-run ``claude setup-token``
and call :func:`store_token` with the new value.
"""

from __future__ import annotations

import json
import os
import re
import time
from pathlib import Path

import click
from rich.console import Console
from rich.panel import Panel

console = Console()

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

TOKEN_FILE = Path("~/.missy/secrets/anthropic-token.json").expanduser()

# Setup-tokens are valid for approximately 3 hours.
SETUP_TOKEN_TTL_SECONDS = 3 * 3600
# Warn if fewer than 20 minutes remain.
REFRESH_WARN_MARGIN = 20 * 60

_API_KEY_PATTERN = re.compile(r"^sk-ant-api\d{2}-[A-Za-z0-9\-_]{80,}$")
_SETUP_TOKEN_PATTERN = re.compile(r"^sk-ant-oat\d{2}-[A-Za-z0-9\-_]{60,}$")

TOS_WARNING = (
    "[yellow bold]ToS Warning[/]\n\n"
    "Anthropic updated their Terms of Service on [bold]February 19, 2026[/] to\n"
    "prohibit the use of OAuth setup-tokens (sk-ant-oat01-...) in third-party\n"
    "tools.  Using a setup-token in Missy may violate the Anthropic ToS.\n\n"
    "The [bold green]API key[/] path ([bold]missy setup → option 1[/]) is fully compliant.\n"
    "Only proceed if you understand and accept this risk."
)

# ---------------------------------------------------------------------------
# Token classification
# ---------------------------------------------------------------------------


def classify_token(token: str) -> str:
    """Return ``'api_key'``, ``'setup_token'``, or ``'unknown'``."""
    t = token.strip()
    if _API_KEY_PATTERN.match(t):
        return "api_key"
    if _SETUP_TOKEN_PATTERN.match(t):
        return "setup_token"
    # Partial heuristics for incomplete/mangled tokens.
    if t.startswith("sk-ant-api"):
        return "api_key"
    if t.startswith("sk-ant-oat"):
        return "setup_token"
    return "unknown"


# ---------------------------------------------------------------------------
# Token persistence
# ---------------------------------------------------------------------------


def store_token(token: str, token_type: str, issued_at: int | None = None) -> None:
    """Write token data to TOKEN_FILE atomically (mode 0o600)."""
    TOKEN_FILE.parent.mkdir(parents=True, mode=0o700, exist_ok=True)
    data = {
        "provider": "anthropic",
        "token_type": token_type,
        "token": token,
        "issued_at": issued_at or int(time.time()),
    }
    tmp = TOKEN_FILE.with_suffix(".tmp")
    tmp.write_text(json.dumps(data, indent=2), encoding="utf-8")
    tmp.chmod(0o600)
    tmp.replace(TOKEN_FILE)


def load_token() -> dict | None:
    """Return the stored token dict, or None if not present/readable."""
    if not TOKEN_FILE.exists():
        return None
    try:
        return json.loads(TOKEN_FILE.read_text(encoding="utf-8"))
    except Exception:
        return None


def is_token_expiring(token_data: dict) -> bool:
    """Return True if a setup-token is within the refresh-warning margin."""
    if token_data.get("token_type") != "setup_token":
        return False  # API keys do not expire.
    issued_at = token_data.get("issued_at", 0)
    age = time.time() - issued_at
    remaining = SETUP_TOKEN_TTL_SECONDS - age
    return remaining < REFRESH_WARN_MARGIN


def remind_refresh() -> None:
    """Print a renewal reminder for an expiring setup-token."""
    console.print(
        Panel(
            "Your Anthropic setup-token is expiring soon.\n\n"
            "Renew it by running:\n"
            "  [bold cyan]claude setup-token[/]\n\n"
            "Then update Missy with:\n"
            "  [bold cyan]missy setup[/]  (re-run the wizard)\n"
            "  or set [bold]ANTHROPIC_API_KEY[/] to the new token.",
            title="[yellow]Setup-token Expiring[/]",
            border_style="yellow",
        )
    )


# ---------------------------------------------------------------------------
# Vault integration
# ---------------------------------------------------------------------------


def _try_store_in_vault(token: str, vault_dir: str = "~/.missy/secrets") -> str | None:
    """Store *token* in the Missy encrypted vault.

    Returns the vault reference string (``vault://anthropic_api_key``) on
    success, or None if the vault is unavailable.
    """
    try:
        from missy.security.vault import Vault
        v = Vault(vault_dir)
        v.set("anthropic_api_key", token)
        return "vault://anthropic_api_key"
    except Exception as exc:
        console.print(f"  [yellow]Vault storage failed:[/] {exc}")
        return None


# ---------------------------------------------------------------------------
# Setup-token paste flow
# ---------------------------------------------------------------------------


def run_anthropic_setup_token_flow() -> str | None:
    """Guide the user through the Claude Code setup-token paste flow.

    Steps:
    1. Show ToS warning and require acknowledgement.
    2. Check whether the ``claude`` CLI is in PATH.
    3. Instruct the user to run ``claude setup-token``.
    4. Prompt for paste, validate format.
    5. Persist token and return it.

    Returns:
        The setup-token string, or None if aborted.
    """
    console.print(Panel(TOS_WARNING, title="[yellow bold]! Anthropic ToS Warning[/]", border_style="yellow"))
    if not click.confirm("\n  I understand and accept the ToS risk — continue?", default=False):
        console.print("  [dim]Setup-token flow aborted.[/]")
        return None

    # Check for claude CLI.
    import shutil
    claude_bin = shutil.which("claude")
    if claude_bin:
        console.print(f"\n  [green]Found Claude Code CLI:[/] {claude_bin}")
        console.print(
            "\n  Run the following command in a [bold]separate terminal[/]:\n\n"
            "    [bold cyan]claude setup-token[/]\n\n"
            "  Complete the browser authorization, then paste the token below."
        )
    else:
        console.print(
            "\n  [yellow]Claude Code CLI not found in PATH.[/]\n\n"
            "  To generate a setup-token:\n"
            "    1. Install Claude Code: [cyan]npm install -g @anthropic-ai/claude-code[/]\n"
            "    2. Run: [bold cyan]claude setup-token[/]\n"
            "    3. Complete browser authorization\n"
            "    4. Copy the printed token (starts with sk-ant-oat01-)\n\n"
            "  Then paste it below."
        )

    # Paste loop.
    while True:
        raw = click.prompt("\n  Paste setup-token", hide_input=True, default="").strip()
        if not raw:
            if click.confirm("  Abort setup-token flow?", default=True):
                return None
            continue

        # Strip shell assignment patterns.
        if "=" in raw:
            raw = raw.split("=", 1)[1].strip()
        raw = raw.strip("\"'")

        kind = classify_token(raw)
        if kind == "api_key":
            console.print(
                "  [yellow]This looks like a regular API key (sk-ant-api...), not a setup-token.[/]\n"
                "  Use the [bold]API key[/] auth method instead."
            )
            if not click.confirm("  Use it as an API key anyway?", default=False):
                continue
            return raw

        if kind == "unknown":
            console.print(
                f"  [yellow]Unrecognised token format.[/]  "
                f"Expected sk-ant-oat01-... (got: {raw[:20]}…)"
            )
            if not click.confirm("  Use this value anyway?", default=False):
                continue

        store_token(raw, token_type="setup_token")
        console.print("  [green]Setup-token accepted[/] (expires in ≈3 hours).")
        console.print(f"  [dim]Stored at {TOKEN_FILE}[/]")
        return raw


# ---------------------------------------------------------------------------
# API-key vault flow
# ---------------------------------------------------------------------------


def run_anthropic_vault_flow(api_key: str, vault_dir: str = "~/.missy/secrets") -> str:
    """Offer to store *api_key* in the encrypted vault.

    Returns either ``vault://anthropic_api_key`` (if stored) or the raw key
    (if vault storage was declined or failed).
    """
    console.print(
        "\n  [dim]You can store this key in the Missy encrypted vault (ChaCha20-Poly1305).\n"
        "  The config will then reference it as [bold]vault://anthropic_api_key[/]\n"
        "  instead of embedding the raw key in config.yaml.[/]"
    )
    if click.confirm("  Store in vault?", default=True):
        ref = _try_store_in_vault(api_key, vault_dir)
        if ref:
            store_token(api_key, token_type="api_key")
            console.print(f"  [green]Key stored in vault.[/]  Config will use [bold]{ref}[/]")
            return ref
    return api_key


# ---------------------------------------------------------------------------
# Runtime helper
# ---------------------------------------------------------------------------


def get_current_token(vault_dir: str = "~/.missy/secrets") -> str | None:
    """Return the active Anthropic token/key for runtime use.

    Resolution order:
    1. ``ANTHROPIC_API_KEY`` environment variable.
    2. Token stored in ``~/.missy/secrets/anthropic-token.json``.
    3. Vault lookup for ``anthropic_api_key``.

    Emits a renewal reminder if a setup-token is near expiry.
    """
    # 1. Env var.
    env = os.environ.get("ANTHROPIC_API_KEY")
    if env:
        return env

    # 2. Stored token file.
    data = load_token()
    if data:
        if is_token_expiring(data):
            remind_refresh()
        return data.get("token")

    # 3. Vault.
    try:
        from missy.security.vault import Vault
        v = Vault(vault_dir)
        return v.get("anthropic_api_key")
    except Exception:
        return None
